### ISSUE TITLE
[BUG] Assertion error when data file is manipulated before start

### ISSUE THREAD

**Issue by StanleyNeoh** [AY2223S2-CS2103T-W14-1/tp#210]
Only a problem when assertions are on I think, it still runs properly when the jar version is used

**Comment by immanuelhume** [comment]
dis is referring to when the .json file format is invalid right

**Comment by Douglch** [comment]
do ya know which class the assertion error's coming from

**Comment by RubyNguyen07** [comment]
Hmm probably coming from JsonUtilTest.java file right?
