### ISSUE TITLE
[PE-D][Tester A] Validation allows symbols in client names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W14-1/tp#222]
I read through the UG and saw the note on client names stating:

" A note on names: Mycelium supports names with s/o and d/o in them. For example, Alice Baker s/o Bob Baker is a valid name. In fact, X Æ A-12 is also a valid name in Mycelium. "

Not sure if using @@@@ in a client name is acceptable for this case. Perhaps just allowing the symbol "/" for client names in this case is enough?

![image.png](https://raw.githubusercontent.com/Irminrics/ped/main/files/27b5dd09-5fbb-4d07-a402-462c1c7fb571.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Irminrics/ped#2

**Comment by Douglch** [comment]
Mycelium supports all types of names!

**Comment by immanuelhume** [comment]
Can also add a note about how sometimes you might only have access to a client's username, and not their real name
