### ISSUE TITLE
[Developer Guide] Model Component consistent issue

### ISSUE THREAD

**Issue by StanleyNeoh** [AY2223S2-CS2103T-W14-1/tp#289]
![image](https://user-images.githubusercontent.com/95394480/230782948-63406bca-274f-4eb1-9631-94606ab694bc.png)

There is a number of issues here:
- [x] mobileNumber in diagram but phone number in text
- [x] attributes in the text is not consistent.
- [ ] maybe some re-organisation is needed

**Comment by RubyNguyen07** [comment]
Plus that for acceptedOn, it should be LocalDate instead of :LocalDate
