### ISSUE TITLE
[UG] Inconsistent format for project status

### ISSUE THREAD

**Issue by immanuelhume** [AY2223S2-CS2103T-W14-1/tp#40]
The way a project's status is described is not consistent. Perhaps we should choose one or the other.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/47441677/222444049-f320f4b6-bc86-4203-9452-94173bab990c.png">
<img width="484" alt="image" src="https://user-images.githubusercontent.com/47441677/222444126-424fcf1e-f4f0-4555-bc86-58ce121a666f.png">

**Comment by RubyNguyen07** [comment]
Hmm true, how about just bold texts like in the notion note?
