### ISSUE TITLE
Better command format in error messages

### ISSUE THREAD

**Issue by immanuelhume** [AY2223S2-CS2103T-W14-1/tp#91]
Currently, we return something like this upon an invalid input.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/47441677/224992104-b1b1faec-3cab-48d0-8059-26b785594932.png">

It would be better to indicate which commands are optional, and which are compulsory. Perhaps we should add this to UG as well. Something like this?

```
Arguments: -cn CLIENT NAME -e CLIENT EMAIL [-src CLIENT SOURCE] [-mn MOBILE NUMBER] [-y YEAR OF BIRTH]
```

Or
```
Compulsory arguments: -cn CLIENT NAME -e CLIENT EMAIL 
Optional arguments: -src CLIENT SOURCE -mn MOBILE NUMBER -y YEAR OF BIRTH
```

**Comment by sachindavid96** [comment]
Will do this

**Comment by StanleyNeoh** [comment]
Fixed in merge.
